// Shared helpers for the read-only spec reports (spec §1 universal controls, §8.2 export rules).

export type DatePreset = 'TODAY' | 'YESTERDAY' | 'THIS_WEEK' | 'THIS_MONTH' | 'LAST_MONTH' | 'CUSTOM';

export const DATE_PRESETS: { id: DatePreset; label: string }[] = [
  { id: 'TODAY', label: 'Today' },
  { id: 'YESTERDAY', label: 'Yesterday' },
  { id: 'THIS_WEEK', label: 'This Week' },
  { id: 'THIS_MONTH', label: 'This Month' },
  { id: 'LAST_MONTH', label: 'Last Month' },
  { id: 'CUSTOM', label: 'Custom Range' },
];

const ymd = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

/** Resolve a preset against the business date (YYYY-MM-DD). Week starts Monday. */
export const resolvePreset = (preset: DatePreset, businessDate: string): { from: string; to: string } | null => {
  const [y, m, d] = businessDate.split('-').map(Number);
  const today = new Date(y, m - 1, d);
  switch (preset) {
    case 'TODAY':
      return { from: businessDate, to: businessDate };
    case 'YESTERDAY': {
      const p = new Date(y, m - 1, d - 1);
      return { from: ymd(p), to: ymd(p) };
    }
    case 'THIS_WEEK': {
      const offset = (today.getDay() + 6) % 7;
      return { from: ymd(new Date(y, m - 1, d - offset)), to: businessDate };
    }
    case 'THIS_MONTH':
      return { from: ymd(new Date(y, m - 1, 1)), to: businessDate };
    case 'LAST_MONTH':
      return { from: ymd(new Date(y, m - 2, 1)), to: ymd(new Date(y, m - 1, 0)) };
    default:
      return null;
  }
};

/** 'YYYY-MM' → 'Oct 2026'. */
export const monthLabel = (ym: string) => {
  const [y, m] = ym.split('-').map(Number);
  return new Date(y, m - 1, 1).toLocaleDateString('en-GB', { month: 'short', year: 'numeric' });
};

const cell = (v: unknown) => {
  if (v === null || v === undefined) return '';
  if (typeof v === 'number') return String(v);
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

/**
 * Excel-compatible CSV: metadata block (report, branch, range, filters, generated by/at),
 * a blank line, then typed numeric columns exactly as on screen.
 */
export const downloadReportCsv = (
  fileName: string,
  meta: [string, string][],
  sections: { title?: string; headers: string[]; rows: unknown[][] }[]
) => {
  const lines: string[] = meta.map(([k, v]) => `${cell(k)},${cell(v)}`);
  for (const s of sections) {
    lines.push('');
    if (s.title) lines.push(cell(s.title));
    lines.push(s.headers.map(cell).join(','));
    for (const r of s.rows) lines.push(r.map(cell).join(','));
  }
  const blob = new Blob(['﻿' + lines.join('\n')], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
};
