import React, { useEffect, useMemo, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { useRouter } from '@/context/RouterContext';
import { salonService } from '@/services';
import { Branch, StaffMember, StaffSalaryReport, StaffSalaryReportQuery } from '@/types/salon';
import { formatCurrency } from '@/lib/formatters';
import { AccessDeniedView } from '@/features/scaffold/AccessDeniedView';
import { AlertCircle, ExternalLink, FileSpreadsheet, Printer, RefreshCw, Wallet } from 'lucide-react';
import { downloadReportCsv, monthLabel } from './reportUtils';

const STATUS_CLS: Record<string, string> = {
  PAID: 'bg-emerald-100 text-emerald-800',
  PARTIALLY_PAID: 'bg-amber-100 text-amber-800',
  FINALIZED: 'bg-indigo-100 text-indigo-800',
};
const field = 'w-full text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 bg-white focus:ring-2 focus:ring-indigo-500';
const label = 'block text-[10px] font-semibold text-slate-500 uppercase tracking-wide mb-1';

/**
 * Spec §10.2 Staff Salary Report — read-only. Date basis: payroll period of FINALIZED runs;
 * paid date shown separately. Salary payments settle the liability (never a second expense).
 */
export const StaffSalaryReportPage: React.FC = () => {
  const { user, demoDate } = useAuth();
  const { navigate } = useRouter();
  if (!user || (user.role !== 'SUPER_ADMIN' && user.role !== 'ADMIN')) {
    return <AccessDeniedView attemptedPath="/reports/staff-salary" />;
  }
  const isSuperAdmin = user.role === 'SUPER_ADMIN';
  const thisMonth = (demoDate || new Date().toISOString().slice(0, 10)).slice(0, 7);
  const yearStart = `${thisMonth.slice(0, 4)}-01`;

  const [branches, setBranches] = useState<Branch[]>([]);
  const [staff, setStaff] = useState<StaffMember[]>([]);
  const initial: StaffSalaryReportQuery = { branchId: isSuperAdmin ? 'ALL' : user.branchId || '', fromMonth: yearStart, toMonth: thisMonth };
  const [form, setForm] = useState<StaffSalaryReportQuery>(initial);
  const [applied, setApplied] = useState<StaffSalaryReportQuery>(initial);
  const [report, setReport] = useState<StaffSalaryReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    salonService.getBranches().then(setBranches).catch(() => undefined);
  }, []);
  useEffect(() => {
    salonService.getStaff(form.branchId || 'ALL').then(setStaff).catch(() => setStaff([]));
  }, [form.branchId]);
  useEffect(() => {
    let alive = true;
    setLoading(true);
    setError(null);
    const q = Object.fromEntries(Object.entries(applied).filter(([, v]) => v)) as StaffSalaryReportQuery;
    salonService.getStaffSalaryReport(q)
      .then((r) => alive && setReport(r))
      .catch((e) => alive && setError(e.message || 'Failed to load the salary report.'))
      .finally(() => alive && setLoading(false));
    return () => { alive = false; };
  }, [applied]);

  const designations = useMemo(() => [...new Set(staff.map((s) => s.designation).filter(Boolean))].sort(), [staff]);
  const branchName = (id?: string) => (!id || id === 'ALL' ? 'All Branches' : branches.find((b) => b.id === id)?.name || id);
  const t = report?.totals;

  const exportCsv = () => {
    if (!report) return;
    downloadReportCsv(`Staff_Salary_${applied.fromMonth}_${applied.toMonth}.csv`, [
      ['Report', 'Staff Salary Report'],
      ['Branch', branchName(applied.branchId)],
      ['Payroll period', `${applied.fromMonth} to ${applied.toMonth}`],
      ['Date basis', report.dateBasis],
      ['Filters', [applied.staffId && `Staff: ${staff.find((s) => s.id === applied.staffId)?.name}`, applied.designation && `Designation: ${applied.designation}`,
        applied.paymentStatus && `Status: ${applied.paymentStatus}`, applied.paymentMethod && `Method: ${applied.paymentMethod}`].filter(Boolean).join('; ') || 'None'],
      ['Generated by', user.name],
      ['Generated at', new Date().toLocaleString()],
    ], [{
      headers: ['Period', 'Payslip #', 'Staff', 'Code', 'Branch', 'Basic', 'Attendance', 'OT', 'Allowances', 'Deductions', 'Advance Recovery', 'Gross', 'Net', 'Paid', 'Outstanding', 'Status', 'Paid Date', 'Processed By'],
      rows: [
        ...report.rows.map((r) => [r.period, r.payslipNumber, r.staffName, r.employeeCode, r.branchName, r.basic, r.attendance, r.overtime, r.allowances,
          r.deductions, r.advanceRecovery, r.gross, r.net, r.paid, r.outstanding, r.status, r.paidDate ?? '', r.processedBy ?? '']),
        ['TOTAL', '', '', '', '', t!.basic, t!.attendance, t!.overtime, t!.allowances, t!.deductions, t!.advanceRecovery, t!.gross, t!.net, t!.paid, t!.outstanding, '', '', ''],
      ],
    }]);
  };

  const kpis: [string, number | undefined, string][] = [
    ['Basic', t?.basic, 'text-slate-900'],
    ['Attendance Impact', t?.attendance, 'text-rose-600'],
    ['Overtime', t?.overtime, 'text-indigo-600'],
    ['Allowances', t?.allowances, 'text-emerald-600'],
    ['Deductions', t?.deductions, 'text-rose-600'],
    ['Gross', t?.gross, 'text-slate-900'],
    ['Net Salary', t?.net, 'text-indigo-700'],
    ['Paid', t?.paid, 'text-emerald-600'],
    ['Outstanding', t?.outstanding, 'text-amber-600'],
  ];

  return (
    <div className="p-4 sm:p-6 max-w-7xl mx-auto space-y-4 font-sans">
      <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-indigo-50 text-indigo-600 rounded-xl"><Wallet className="w-5 h-5" /></div>
          <div>
            <h1 className="text-xl font-bold text-slate-900">Staff Salary Report</h1>
            <p className="text-xs text-slate-500">Finalized payroll by period — basic, attendance impact, overtime, allowances, deductions, paid and outstanding.</p>
          </div>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={() => navigate('/accounts/payroll')} className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-slate-200 bg-white rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50">
            <ExternalLink className="w-3.5 h-3.5" /> Open Payroll
          </button>
          <button onClick={exportCsv} disabled={!report?.rows.length} className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-slate-200 bg-white rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50">
            <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600" /> Excel
          </button>
          <button onClick={() => window.print()} className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-slate-200 bg-white rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50">
            <Printer className="w-3.5 h-3.5" /> Print / PDF
          </button>
        </div>
      </div>

      {/* Filter row */}
      <form
        onSubmit={(e) => { e.preventDefault(); setApplied({ ...form }); }}
        className="bg-white p-3 rounded-xl border border-slate-100 shadow-sm grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-2 items-end print:hidden"
      >
        {isSuperAdmin && (
          <div>
            <label className={label}>Branch</label>
            <select className={field} value={form.branchId} onChange={(e) => setForm({ ...form, branchId: e.target.value, staffId: undefined })}>
              <option value="ALL">All Branches</option>
              {branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}
            </select>
          </div>
        )}
        <div>
          <label className={label}>From Period</label>
          <input type="month" className={field} value={form.fromMonth} max={form.toMonth} required onChange={(e) => setForm({ ...form, fromMonth: e.target.value })} />
        </div>
        <div>
          <label className={label}>To Period</label>
          <input type="month" className={field} value={form.toMonth} min={form.fromMonth} required onChange={(e) => setForm({ ...form, toMonth: e.target.value })} />
        </div>
        <div>
          <label className={label}>Staff</label>
          <select className={field} value={form.staffId || ''} onChange={(e) => setForm({ ...form, staffId: e.target.value || undefined })}>
            <option value="">All Staff</option>
            {staff.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
          </select>
        </div>
        <div>
          <label className={label}>Designation</label>
          <select className={field} value={form.designation || ''} onChange={(e) => setForm({ ...form, designation: e.target.value || undefined })}>
            <option value="">All</option>
            {designations.map((d) => <option key={d} value={d}>{d}</option>)}
          </select>
        </div>
        <div>
          <label className={label}>Payment Status</label>
          <select className={field} value={form.paymentStatus || ''} onChange={(e) => setForm({ ...form, paymentStatus: (e.target.value || undefined) as StaffSalaryReportQuery['paymentStatus'] })}>
            <option value="">All</option>
            <option value="FINALIZED">Unpaid</option>
            <option value="PARTIALLY_PAID">Partially Paid</option>
            <option value="PAID">Paid</option>
          </select>
        </div>
        <div>
          <label className={label}>Paid Via</label>
          <select className={field} value={form.paymentMethod || ''} onChange={(e) => setForm({ ...form, paymentMethod: (e.target.value || undefined) as StaffSalaryReportQuery['paymentMethod'] })}>
            <option value="">Any</option>
            <option value="CASH">Cash</option>
            <option value="ONLINE">Online</option>
          </select>
        </div>
        <div className="flex gap-1.5">
          <button type="submit" className="flex-1 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-semibold">Apply</button>
          <button type="button" onClick={() => { setForm(initial); setApplied(initial); }} className="px-2.5 py-1.5 border border-slate-200 rounded-lg text-xs text-slate-600 hover:bg-slate-50" title="Reset">
            <RefreshCw className="w-3.5 h-3.5" />
          </button>
        </div>
      </form>

      <p className="text-[11px] text-slate-500">
        <span className="font-semibold">{branchName(applied.branchId)}</span> · Payroll period {monthLabel(applied.fromMonth)} – {monthLabel(applied.toMonth)} ·
        {' '}Date basis: finalized payroll period (draft and cancelled runs excluded); paid date shown separately. Paid / outstanding reflect payments to date.
      </p>

      {error && (
        <div className="p-3 rounded-lg bg-rose-50 border border-rose-200 text-rose-800 text-xs flex items-center gap-2"><AlertCircle className="w-4 h-4" /> {error}</div>
      )}

      {/* KPI strip */}
      <div className="grid grid-cols-3 sm:grid-cols-5 lg:grid-cols-9 gap-2">
        {kpis.map(([k, v, cls]) => (
          <div key={k} className="bg-white border border-slate-100 rounded-lg px-3 py-2 shadow-sm">
            <div className="text-[10px] font-semibold text-slate-400 uppercase tracking-wide">{k}</div>
            <div className={`text-sm font-bold ${cls}`}>{formatCurrency(v ?? 0)}</div>
          </div>
        ))}
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl border border-slate-100 shadow-sm overflow-x-auto">
        <table className="w-full text-[11px] whitespace-nowrap">
          <thead className="bg-slate-100/80 text-slate-600 font-semibold">
            <tr>
              {['Period', 'Staff', 'Branch', 'Basic', 'Attendance', 'OT', 'Allowances', 'Deductions', 'Gross', 'Net', 'Paid', 'Outstanding', 'Status', 'Paid Date', 'Processed By'].map((h, i) => (
                <th key={h} className={`py-2 px-2.5 ${i >= 3 && i <= 11 ? 'text-right' : 'text-left'}`}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {loading && <tr><td colSpan={15} className="py-8 text-center text-slate-400">Loading…</td></tr>}
            {!loading && report?.rows.length === 0 && (
              <tr><td colSpan={15} className="py-8 text-center text-slate-400">No finalized payroll in this period. Finalize a payroll run first.</td></tr>
            )}
            {!loading && report?.rows.map((r) => (
              <tr key={r.payslipId} className="hover:bg-slate-50/60">
                <td className="py-1.5 px-2.5">{monthLabel(r.period)}<div className="text-[10px] text-slate-400">{r.payslipNumber}</div></td>
                <td className="py-1.5 px-2.5"><div className="font-semibold text-slate-900">{r.staffName}</div><div className="text-[10px] text-slate-400">{r.employeeCode} • {r.designation}</div></td>
                <td className="py-1.5 px-2.5">{r.branchName}</td>
                <td className="py-1.5 px-2.5 text-right">{formatCurrency(r.basic)}</td>
                <td className="py-1.5 px-2.5 text-right text-rose-600">{r.attendance ? formatCurrency(r.attendance) : '—'}</td>
                <td className="py-1.5 px-2.5 text-right text-indigo-600">{r.overtime ? formatCurrency(r.overtime) : '—'}</td>
                <td className="py-1.5 px-2.5 text-right text-emerald-600">{r.allowances ? formatCurrency(r.allowances) : '—'}</td>
                <td className="py-1.5 px-2.5 text-right text-rose-600" title={r.advanceRecovery ? `Includes advance recovery ${formatCurrency(r.advanceRecovery)}` : undefined}>
                  {r.deductions ? formatCurrency(-r.deductions) : '—'}
                </td>
                <td className="py-1.5 px-2.5 text-right">{formatCurrency(r.gross)}</td>
                <td className="py-1.5 px-2.5 text-right font-bold text-slate-900">{formatCurrency(r.net)}</td>
                <td className="py-1.5 px-2.5 text-right text-emerald-600">{formatCurrency(r.paid)}</td>
                <td className="py-1.5 px-2.5 text-right font-semibold text-amber-600">{formatCurrency(r.outstanding)}</td>
                <td className="py-1.5 px-2.5"><span className={`px-1.5 py-0.5 rounded text-[10px] font-semibold ${STATUS_CLS[r.status]}`}>{r.status === 'FINALIZED' ? 'UNPAID' : r.status.replace('_', ' ')}</span></td>
                <td className="py-1.5 px-2.5">{r.paidDate ?? '—'}</td>
                <td className="py-1.5 px-2.5">{r.processedBy ?? '—'}</td>
              </tr>
            ))}
          </tbody>
          {!loading && t && report!.rows.length > 0 && (
            <tfoot className="bg-slate-50 font-bold text-slate-900 border-t-2 border-slate-200">
              <tr>
                <td className="py-2 px-2.5" colSpan={3}>Totals ({report!.rows.length} payslips)</td>
                <td className="py-2 px-2.5 text-right">{formatCurrency(t.basic)}</td>
                <td className="py-2 px-2.5 text-right text-rose-600">{formatCurrency(t.attendance)}</td>
                <td className="py-2 px-2.5 text-right">{formatCurrency(t.overtime)}</td>
                <td className="py-2 px-2.5 text-right">{formatCurrency(t.allowances)}</td>
                <td className="py-2 px-2.5 text-right text-rose-600">{formatCurrency(t.deductions ? -t.deductions : 0)}</td>
                <td className="py-2 px-2.5 text-right">{formatCurrency(t.gross)}</td>
                <td className="py-2 px-2.5 text-right">{formatCurrency(t.net)}</td>
                <td className="py-2 px-2.5 text-right text-emerald-600">{formatCurrency(t.paid)}</td>
                <td className="py-2 px-2.5 text-right text-amber-600">{formatCurrency(t.outstanding)}</td>
                <td colSpan={3} />
              </tr>
            </tfoot>
          )}
        </table>
      </div>
      <p className="text-[10px] text-slate-400">
        Net = Basic + Overtime + Allowances + Attendance impact − Deductions (incl. salary-advance recovery). Generated by {user.name} · {new Date().toLocaleString()}
      </p>
    </div>
  );
};
