import React, { useEffect, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { useRouter } from '@/context/RouterContext';
import { salonService } from '@/services';
import { Branch, StaffCommissionReport, StaffCommissionReportQuery, StaffMember } from '@/types/salon';
import { formatCurrency } from '@/lib/formatters';
import { AccessDeniedView } from '@/features/scaffold/AccessDeniedView';
import { AlertCircle, ExternalLink, FileSpreadsheet, Percent, Printer, RefreshCw } from 'lucide-react';
import { DATE_PRESETS, DatePreset, downloadReportCsv, resolvePreset } from './reportUtils';

const field = 'w-full text-xs border border-slate-200 rounded-lg px-2.5 py-1.5 bg-white focus:ring-2 focus:ring-purple-500';
const label = 'block text-[10px] font-semibold text-slate-500 uppercase tracking-wide mb-1';

type Form = StaffCommissionReportQuery & { preset: DatePreset };

/**
 * Spec §10.3 Staff Commission Report — read-only. Date basis: commission EARN / REVERSAL event date
 * (a refund in October is an October reversal); payouts by paid date. Base excludes discounts, tax and tips.
 * Outstanding = opening liability + earned − reversed − paid.
 */
export const StaffCommissionReportPage: React.FC = () => {
  const { user, demoDate } = useAuth();
  const { navigate } = useRouter();
  if (!user || (user.role !== 'SUPER_ADMIN' && user.role !== 'ADMIN')) {
    return <AccessDeniedView attemptedPath="/reports/staff-commission" />;
  }
  const isSuperAdmin = user.role === 'SUPER_ADMIN';
  const businessDate = demoDate || new Date().toISOString().slice(0, 10);
  const month = resolvePreset('THIS_MONTH', businessDate)!;

  const initial: Form = { preset: 'THIS_MONTH', branchId: isSuperAdmin ? 'ALL' : user.branchId || '', startDate: month.from, endDate: month.to };
  const [branches, setBranches] = useState<Branch[]>([]);
  const [staff, setStaff] = useState<StaffMember[]>([]);
  const [form, setForm] = useState<Form>(initial);
  const [applied, setApplied] = useState<Form>(initial);
  const [report, setReport] = useState<StaffCommissionReport | null>(null);
  const [tab, setTab] = useState<'STAFF' | 'LINES'>('STAFF');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    salonService.getBranches().then(setBranches).catch(() => undefined);
  }, []);
  useEffect(() => {
    salonService.getStaff(form.branchId || 'ALL').then(setStaff).catch(() => setStaff([]));
  }, [form.branchId]);
  useEffect(() => {
    let alive = true;
    setLoading(true);
    setError(null);
    const { preset: _p, ...rest } = applied;
    const q = Object.fromEntries(Object.entries(rest).filter(([, v]) => v)) as unknown as StaffCommissionReportQuery;
    salonService.getStaffCommissionReport(q)
      .then((r) => alive && setReport(r))
      .catch((e) => alive && setError(e.message || 'Failed to load the commission report.'))
      .finally(() => alive && setLoading(false));
    return () => { alive = false; };
  }, [applied]);

  const setPreset = (preset: DatePreset) => {
    const r = resolvePreset(preset, businessDate);
    setForm({ ...form, preset, ...(r ? { startDate: r.from, endDate: r.to } : {}) });
  };
  const branchName = (id?: string) => (!id || id === 'ALL' ? 'All Branches' : branches.find((b) => b.id === id)?.name || id);
  const t = report?.totals;

  const exportCsv = () => {
    if (!report) return;
    downloadReportCsv(`Staff_Commission_${applied.startDate}_${applied.endDate}.csv`, [
      ['Report', 'Staff Commission Report'],
      ['Branch', branchName(applied.branchId)],
      ['Date range', `${applied.startDate} to ${applied.endDate}`],
      ['Date basis', report.dateBasis],
      ['Filters', [applied.staffId && `Staff: ${staff.find((s) => s.id === applied.staffId)?.name}`, applied.source && `Source: ${applied.source}`,
        applied.invoiceNumber && `Invoice: ${applied.invoiceNumber}`].filter(Boolean).join('; ') || 'None'],
      ['Generated by', user.name],
      ['Generated at', new Date().toLocaleString()],
    ], [
      {
        title: 'By staff',
        headers: ['Staff', 'Code', 'Attributed Net Sales', 'Opening Liability', 'Earned', 'Reversed', 'Net', 'Paid', 'Outstanding'],
        rows: [
          ...report.byStaff.map((s) => [s.staffName, s.employeeCode, s.attributedNetSales, s.openingLiability, s.earned, s.reversed, s.net, s.paid, s.outstanding]),
          ['TOTAL', '', t!.attributedNetSales, t!.openingLiability, t!.earned, t!.reversed, t!.net, t!.paid, t!.outstanding],
        ],
      },
      {
        title: 'Commission events',
        headers: ['Date', 'Staff', 'Invoice', 'Customer', 'Service / Package Component', 'Source', 'Event', 'Attributed Net Sales', 'Rate %', 'Earned', 'Reversed', 'Net', 'Run'],
        rows: report.rows.map((r) => [r.date, r.staffName, r.invoiceNumber, r.customer, r.itemName, r.source, r.eventType, r.attributedNetSales, r.rateSnapshot, r.earned, r.reversed, r.net, r.runStatus]),
      },
    ]);
  };

  const kpis: [string, number | undefined, string][] = [
    ['Attributed Net Sales', t?.attributedNetSales, 'text-slate-900'],
    ['Commission Earned', t?.earned, 'text-emerald-600'],
    ['Commission Reversed', t?.reversed ? -t.reversed : 0, 'text-rose-600'],
    ['Net Commission', t?.net, 'text-purple-700'],
    ['Paid', t?.paid, 'text-emerald-600'],
    ['Outstanding', t?.outstanding, 'text-amber-600'],
  ];

  return (
    <div className="p-4 sm:p-6 max-w-7xl mx-auto space-y-4 font-sans">
      <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-purple-50 text-purple-600 rounded-xl"><Percent className="w-5 h-5" /></div>
          <div>
            <h1 className="text-xl font-bold text-slate-900">Staff Commission Report</h1>
            <p className="text-xs text-slate-500">Attributed net sales, rate snapshots, commission earned / reversed / paid / outstanding.</p>
          </div>
        </div>
        <div className="flex gap-2 print:hidden">
          <button onClick={() => navigate('/accounts/commission')} className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-slate-200 bg-white rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50">
            <ExternalLink className="w-3.5 h-3.5" /> Open Commission
          </button>
          <button onClick={exportCsv} disabled={!report} className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-slate-200 bg-white rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50">
            <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600" /> Excel
          </button>
          <button onClick={() => window.print()} className="inline-flex items-center gap-1.5 px-3 py-1.5 border border-slate-200 bg-white rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50">
            <Printer className="w-3.5 h-3.5" /> Print / PDF
          </button>
        </div>
      </div>

      <form
        onSubmit={(e) => { e.preventDefault(); setApplied({ ...form }); }}
        className="bg-white p-3 rounded-xl border border-slate-100 shadow-sm grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-2 items-end print:hidden"
      >
        {isSuperAdmin && (
          <div>
            <label className={label}>Branch</label>
            <select className={field} value={form.branchId} onChange={(e) => setForm({ ...form, branchId: e.target.value, staffId: undefined })}>
              <option value="ALL">All Branches</option>
              {branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}
            </select>
          </div>
        )}
        <div>
          <label className={label}>Date</label>
          <select className={field} value={form.preset} onChange={(e) => setPreset(e.target.value as DatePreset)}>
            {DATE_PRESETS.map((p) => <option key={p.id} value={p.id}>{p.label}</option>)}
          </select>
        </div>
        <div>
          <label className={label}>From</label>
          <input type="date" className={field} required disabled={form.preset !== 'CUSTOM'} value={form.startDate} max={form.endDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} />
        </div>
        <div>
          <label className={label}>To</label>
          <input type="date" className={field} required disabled={form.preset !== 'CUSTOM'} value={form.endDate} min={form.startDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} />
        </div>
        <div>
          <label className={label}>Staff</label>
          <select className={field} value={form.staffId || ''} onChange={(e) => setForm({ ...form, staffId: e.target.value || undefined })}>
            <option value="">All Staff</option>
            {staff.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
          </select>
        </div>
        <div>
          <label className={label}>Source</label>
          <select className={field} value={form.source || ''} onChange={(e) => setForm({ ...form, source: (e.target.value || undefined) as StaffCommissionReportQuery['source'] })}>
            <option value="">All</option>
            <option value="SERVICE">Service</option>
            <option value="PACKAGE">Package component</option>
          </select>
        </div>
        <div>
          <label className={label}>Invoice #</label>
          <input className={field} placeholder="INV-…" value={form.invoiceNumber || ''} onChange={(e) => setForm({ ...form, invoiceNumber: e.target.value.trim() || undefined })} />
        </div>
        <div className="flex gap-1.5">
          <button type="submit" className="flex-1 px-3 py-1.5 bg-purple-600 hover:bg-purple-700 text-white rounded-lg text-xs font-semibold">Apply</button>
          <button type="button" onClick={() => { setForm(initial); setApplied(initial); }} className="px-2.5 py-1.5 border border-slate-200 rounded-lg text-xs text-slate-600 hover:bg-slate-50" title="Reset">
            <RefreshCw className="w-3.5 h-3.5" />
          </button>
        </div>
      </form>

      <p className="text-[11px] text-slate-500">
        <span className="font-semibold">{branchName(applied.branchId)}</span> · {applied.startDate} to {applied.endDate} (Asia/Karachi) ·
        {' '}Date basis: commission earn / reversal event date; payouts by paid date. Base = staff-attributed net sales after discount, excluding tax and tips.
      </p>

      {error && (
        <div className="p-3 rounded-lg bg-rose-50 border border-rose-200 text-rose-800 text-xs flex items-center gap-2"><AlertCircle className="w-4 h-4" /> {error}</div>
      )}

      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">
        {kpis.map(([k, v, cls]) => (
          <div key={k} className="bg-white border border-slate-100 rounded-lg px-3 py-2 shadow-sm">
            <div className="text-[10px] font-semibold text-slate-400 uppercase tracking-wide">{k}</div>
            <div className={`text-sm font-bold ${cls}`}>{formatCurrency(v ?? 0)}</div>
          </div>
        ))}
      </div>

      <div className="flex gap-2 print:hidden">
        {(['STAFF', 'LINES'] as const).map((id) => (
          <button key={id} onClick={() => setTab(id)} className={`px-3 py-1.5 rounded-lg text-xs font-semibold ${tab === id ? 'bg-purple-600 text-white' : 'bg-white border border-slate-200 text-slate-600'}`}>
            {id === 'STAFF' ? 'By Staff' : `Commission Events (${report?.rows.length ?? 0})`}
          </button>
        ))}
      </div>

      <div className="bg-white rounded-xl border border-slate-100 shadow-sm overflow-x-auto">
        {tab === 'STAFF' ? (
          <table className="w-full text-[11px] whitespace-nowrap">
            <thead className="bg-slate-100/80 text-slate-600 font-semibold">
              <tr>
                <th className="py-2 px-2.5 text-left">Staff</th>
                {['Attributed Net Sales', 'Opening Liability', 'Earned', 'Reversed', 'Net', 'Paid', 'Outstanding'].map((h) => <th key={h} className="py-2 px-2.5 text-right">{h}</th>)}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {loading && <tr><td colSpan={8} className="py-8 text-center text-slate-400">Loading…</td></tr>}
              {!loading && report?.byStaff.length === 0 && <tr><td colSpan={8} className="py-8 text-center text-slate-400">No commission activity in this range.</td></tr>}
              {!loading && report?.byStaff.map((s) => (
                <tr key={s.staffId} className="hover:bg-slate-50/60">
                  <td className="py-1.5 px-2.5"><div className="font-semibold text-slate-900">{s.staffName}</div><div className="text-[10px] text-slate-400">{s.employeeCode}</div></td>
                  <td className="py-1.5 px-2.5 text-right">{formatCurrency(s.attributedNetSales)}</td>
                  <td className="py-1.5 px-2.5 text-right text-slate-500">{formatCurrency(s.openingLiability)}</td>
                  <td className="py-1.5 px-2.5 text-right text-emerald-600">{formatCurrency(s.earned)}</td>
                  <td className="py-1.5 px-2.5 text-right text-rose-600">{s.reversed ? formatCurrency(-s.reversed) : '—'}</td>
                  <td className="py-1.5 px-2.5 text-right font-bold text-slate-900">{formatCurrency(s.net)}</td>
                  <td className="py-1.5 px-2.5 text-right text-emerald-600">{formatCurrency(s.paid)}</td>
                  <td className="py-1.5 px-2.5 text-right font-semibold text-amber-600">{formatCurrency(s.outstanding)}</td>
                </tr>
              ))}
            </tbody>
            {!loading && t && report!.byStaff.length > 0 && (
              <tfoot className="bg-slate-50 font-bold text-slate-900 border-t-2 border-slate-200">
                <tr>
                  <td className="py-2 px-2.5">Totals</td>
                  <td className="py-2 px-2.5 text-right">{formatCurrency(t.attributedNetSales)}</td>
                  <td className="py-2 px-2.5 text-right">{formatCurrency(t.openingLiability)}</td>
                  <td className="py-2 px-2.5 text-right">{formatCurrency(t.earned)}</td>
                  <td className="py-2 px-2.5 text-right text-rose-600">{formatCurrency(t.reversed ? -t.reversed : 0)}</td>
                  <td className="py-2 px-2.5 text-right">{formatCurrency(t.net)}</td>
                  <td className="py-2 px-2.5 text-right">{formatCurrency(t.paid)}</td>
                  <td className="py-2 px-2.5 text-right text-amber-600">{formatCurrency(t.outstanding)}</td>
                </tr>
              </tfoot>
            )}
          </table>
        ) : (
          <table className="w-full text-[11px] whitespace-nowrap">
            <thead className="bg-slate-100/80 text-slate-600 font-semibold">
              <tr>
                {['Date', 'Staff', 'Invoice', 'Customer', 'Service / Package Component'].map((h) => <th key={h} className="py-2 px-2.5 text-left">{h}</th>)}
                {['Attributed Net', 'Rate', 'Earned', 'Reversed', 'Net'].map((h) => <th key={h} className="py-2 px-2.5 text-right">{h}</th>)}
                <th className="py-2 px-2.5 text-left">Run</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {!loading && report?.rows.length === 0 && <tr><td colSpan={11} className="py-8 text-center text-slate-400">No commission events in this range.</td></tr>}
              {!loading && report?.rows.map((r) => (
                <tr key={r.eventId} className={r.eventType === 'REVERSAL' ? 'bg-rose-50/40' : 'hover:bg-slate-50/60'}>
                  <td className="py-1.5 px-2.5">{r.date}</td>
                  <td className="py-1.5 px-2.5 font-medium text-slate-900">{r.staffName}</td>
                  <td className="py-1.5 px-2.5">{r.invoiceNumber}{r.eventType === 'REVERSAL' && <span className="ml-1 text-[10px] text-rose-600 font-semibold">REVERSAL</span>}</td>
                  <td className="py-1.5 px-2.5">{r.customer}</td>
                  <td className="py-1.5 px-2.5">{r.itemName}</td>
                  <td className="py-1.5 px-2.5 text-right">{formatCurrency(r.attributedNetSales)}</td>
                  <td className="py-1.5 px-2.5 text-right">{r.rateSnapshot}%</td>
                  <td className="py-1.5 px-2.5 text-right text-emerald-600">{r.earned ? formatCurrency(r.earned) : '—'}</td>
                  <td className="py-1.5 px-2.5 text-right text-rose-600">{r.reversed ? formatCurrency(-r.reversed) : '—'}</td>
                  <td className="py-1.5 px-2.5 text-right font-semibold">{formatCurrency(r.net)}</td>
                  <td className="py-1.5 px-2.5"><span className={`px-1.5 py-0.5 rounded text-[10px] font-semibold ${r.runStatus === 'IN_RUN' ? 'bg-indigo-100 text-indigo-800' : 'bg-slate-100 text-slate-600'}`}>{r.runStatus === 'IN_RUN' ? 'In run' : 'Not run'}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
      <p className="text-[10px] text-slate-400">
        Outstanding = Opening liability + Earned − Reversed − Paid. Generated by {user.name} · {new Date().toLocaleString()}
      </p>
    </div>
  );
};
