import React, { ReactNode } from 'react';
import { FileSpreadsheet, FileText, Printer, FileDown, Filter } from 'lucide-react';

export interface ReportShellProps {
  title: string;
  description?: string;
  icon?: React.ElementType;
  /** Filter form row contents (dropdowns, inputs) */
  filterChildren?: ReactNode;
  /** Callback when primary [Filter] button is clicked */
  onFilterSubmit?: (e?: React.FormEvent) => void;
  isFilterLoading?: boolean;
  /** Dark blue accent strip title (defaults to title) */
  bannerTitle?: string;
  /** Metadata audit strip (e.g., branch name, date basis, generated by) */
  metaNotice?: ReactNode;
  /** KPI cards strip */
  kpiStrip?: ReactNode;
  /** Export callbacks */
  onExportExcel?: () => void;
  onExportCsv?: () => void;
  onExportPdf?: () => void;
  onExportPrint?: () => void;
  /** Content: Data Table or custom views */
  children: ReactNode;
}

export const ReportShell: React.FC<ReportShellProps> = ({
  title,
  description,
  icon: Icon,
  filterChildren,
  onFilterSubmit,
  isFilterLoading = false,
  bannerTitle,
  metaNotice,
  kpiStrip,
  onExportExcel,
  onExportCsv,
  onExportPdf,
  onExportPrint,
  children,
}) => {
  return (
    <div className="space-y-4 font-sans text-slate-800 pb-12">
      {/* ── 1. Page Header ── */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div className="flex items-center gap-3">
          {Icon && (
            <div className="p-2.5 bg-blue-50 text-[#2254E1] rounded-xl border border-blue-100 shadow-xs">
              <Icon className="w-5 h-5" />
            </div>
          )}
          <div>
            <h1 className="text-xl font-bold text-slate-900 tracking-tight">{title}</h1>
            {description && <p className="text-xs text-slate-500 mt-0.5">{description}</p>}
          </div>
        </div>
      </div>

      {/* ── 2. Top Filter Header Row (As per Reference Design) ── */}
      {filterChildren && (
        <form
          onSubmit={(e) => {
            e.preventDefault();
            onFilterSubmit?.(e);
          }}
          className="bg-white p-3.5 rounded-xl border border-slate-200/90 shadow-xs print:hidden"
        >
          <div className="flex flex-wrap items-end gap-3">
            <div className="flex-1 flex flex-wrap items-end gap-3 min-w-[280px]">
              {filterChildren}
            </div>

            {/* Primary [Filter] Trigger Button */}
            <div className="shrink-0">
              <button
                type="submit"
                disabled={isFilterLoading}
                className="h-9 px-5 bg-[#0047AB] hover:bg-[#003B8E] active:bg-[#003075] text-white rounded-lg text-xs font-semibold flex items-center justify-center gap-2 shadow-xs transition-colors cursor-pointer disabled:opacity-60"
              >
                <Filter className="w-3.5 h-3.5" />
                <span>{isFilterLoading ? 'Filtering…' : 'Filter'}</span>
              </button>
            </div>
          </div>
        </form>
      )}

      {/* ── 3. Meta Notice / Audit Line ── */}
      {metaNotice && (
        <div className="px-1 text-[11px] text-slate-500 flex items-center gap-2">
          {metaNotice}
        </div>
      )}

      {/* ── 4. KPI Summary Strip (Optional) ── */}
      {kpiStrip && <div className="space-y-2">{kpiStrip}</div>}

      {/* ── 5. Table Header Action Strip (Clean & Light) ── */}
      <div className="flex flex-wrap items-center justify-between gap-2 pt-1 pb-1">
        <div className="text-xs font-semibold text-slate-800 tracking-tight">
          {bannerTitle || title}
        </div>

        {/* Export Actions Strip */}
        <div className="flex items-center gap-1.5 print:hidden">
          {onExportExcel && (
            <button
              type="button"
              onClick={onExportExcel}
              className="h-7 px-2.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 border border-emerald-200 rounded-md text-[11px] font-semibold flex items-center gap-1.5 shadow-2xs transition-colors cursor-pointer"
              title="Export data to Excel spreadsheet"
            >
              <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600" />
              <span>Excel</span>
            </button>
          )}
          {onExportCsv && (
            <button
              type="button"
              onClick={onExportCsv}
              className="h-7 px-2.5 bg-cyan-50 hover:bg-cyan-100 text-cyan-700 border border-cyan-200 rounded-md text-[11px] font-semibold flex items-center gap-1.5 shadow-2xs transition-colors cursor-pointer"
              title="Export raw data to CSV file"
            >
              <FileText className="w-3.5 h-3.5 text-cyan-600" />
              <span>CSV</span>
            </button>
          )}
          {onExportPdf && (
            <button
              type="button"
              onClick={onExportPdf}
              className="h-7 px-2.5 bg-rose-50 hover:bg-rose-100 text-rose-700 border border-rose-200 rounded-md text-[11px] font-semibold flex items-center gap-1.5 shadow-2xs transition-colors cursor-pointer"
              title="Download or Print PDF Document"
            >
              <FileDown className="w-3.5 h-3.5 text-rose-600" />
              <span>PDF</span>
            </button>
          )}
          {onExportPrint && (
            <button
              type="button"
              onClick={onExportPrint}
              className="h-7 px-2.5 bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-200 rounded-md text-[11px] font-semibold flex items-center gap-1.5 shadow-2xs transition-colors cursor-pointer"
              title="Open browser print dialog"
            >
              <Printer className="w-3.5 h-3.5 text-slate-600" />
              <span>Print</span>
            </button>
          )}
        </div>
      </div>

      {/* ── 7. Main Report Body (Landscape Table Container) ── */}
      <div className="w-full">{children}</div>
    </div>
  );
};
